kt=kpitech;
coefficient=techtech;
%case 10
    chosen = nchoosek(1:12,10);
    answer = zeros( 1,10);
    flag=1;
    for i=1:nchoosek(12,10)
        permutation4 = perms(chosen(i,:));
        for j=1:factorial(10)
            permutation=permutation4(j,:);
            
            if coefficient(permutation(1),permutation(2)) < 0 ...
                    || coefficient(permutation(1),permutation(3)) < 0 ...
                    || coefficient(permutation(1),permutation(4)) < 0 ...
                    || coefficient(permutation(1),permutation(5)) < 0 ...
                    || coefficient(permutation(1),permutation(6)) < 0 ...
                    || coefficient(permutation(1),permutation(7)) < 0 ...
                    || coefficient(permutation(1),permutation(8)) < 0 ...
                    || coefficient(permutation(1),permutation(9)) < 0 ...
                    || coefficient(permutation(2),permutation(3)) < 0 ...
                    || coefficient(permutation(2),permutation(4)) < 0 ...
                    || coefficient(permutation(2),permutation(5)) < 0 ...
                    || coefficient(permutation(2),permutation(6)) < 0 ...
                    || coefficient(permutation(2),permutation(7)) < 0 ...
                    || coefficient(permutation(2),permutation(8)) < 0 ...
                    || coefficient(permutation(2),permutation(9)) < 0 ...
                    || coefficient(permutation(3),permutation(4)) < 0 ...
                    || coefficient(permutation(3),permutation(5)) < 0 ...
                    || coefficient(permutation(3),permutation(6)) < 0 ...
                    || coefficient(permutation(3),permutation(7)) < 0 ...
                    || coefficient(permutation(3),permutation(8)) < 0 ...
                    || coefficient(permutation(3),permutation(9)) < 0 ...
                    || coefficient(permutation(4),permutation(5)) < 0 ...
                    || coefficient(permutation(4),permutation(6)) < 0 ...
                    || coefficient(permutation(4),permutation(7)) < 0 ...
                    || coefficient(permutation(4),permutation(8)) < 0 ...
                    || coefficient(permutation(4),permutation(9)) < 0 ...
                    || coefficient(permutation(5),permutation(6)) < 0 ...
                    || coefficient(permutation(5),permutation(7)) < 0 ...
                    || coefficient(permutation(5),permutation(8)) < 0 ...
                    || coefficient(permutation(5),permutation(9)) < 0 ...
                    || coefficient(permutation(6),permutation(7)) < 0 ...
                    || coefficient(permutation(6),permutation(8)) < 0 ...
                    || coefficient(permutation(6),permutation(9)) < 0 ...
                    || coefficient(permutation(7),permutation(8)) < 0 ...
                    || coefficient(permutation(7),permutation(9)) < 0 ...
                continue
            end
            %interaction & oee & kpi need update
            interaction = coefficient(permutation(1),permutation(2)) ...
                * coefficient(permutation(2),permutation(3)) ...
                * coefficient(permutation(3),permutation(4));
            oee = interaction ...
                * kt(permutation(1),1) * kt(permutation(1),8) / kt(permutation(1),2) ...
                * kt(permutation(2),1) * kt(permutation(2),8) / kt(permutation(2),2) ...
                * kt(permutation(3),1) * kt(permutation(3),8) / kt(permutation(3),2) ...
                * kt(permutation(4),1) * kt(permutation(4),8) / kt(permutation(4),2);

            if oee > 5
               answer(flag,:)=permutation;
               answer(flag,11)=oee
               flag=flag+1;       
            end
        end
     end
    delete = ~any(answer,2);
    answer(delete,:)=[];